### ISSUE TITLE
consul-esm could not ping node permission denied

### ISSUE THREAD

**Issue by nitharsan24** [hashicorp/consul-esm#24]
Hello,

we are adding our consul-esm health checks with a go program dynamically, the name of the nodes has an invalid format and consul-esm is not able to ping. The health checks are working fine.
node name has a format like this: worker1.xxx.xxx.xxx_dev-app1.test.com or worker11.xxx.xxx.xxx:dev-app11.test.com

error in log:
**[WARN] could not ping node "worker1.xxx.xxx.xxx_dev-app1.test.com": socket: permission denied**

Here is the related code
[consul-esm/coordinate.go](https://github.com/hashicorp/consul-esm/blob/f55fdd579d038f6fd1104d505cdc104eaafc49e1/coordinate.go#L296)
```
// pingNode runs an ICMP ping against an address and returns the round-trip time.
func pingNode(addr string, method string) (time.Duration, error) {
```

Is it possible to disable the ping on nodes?

Thanks,
Nitharsan

**Comment by kyhavlov** [comment]
Hi nitharsandvag, if you don't want a node to get pinged you can simply omit the `"external-node": "true"` from the meta in its node registration. The "worker1.xxx.xxx.xxx_dev-app1.test.com" string there isn't actually the IP being pinged though, it's the node name, which can be anything as long as the node address is valid and reachable for pings. Hope that helps!

**Comment by KEZHwMlXV1vFzs6QvY8v5WjX5** [comment]
does consul-esm still exec the custom health check if one removes the external-node: true tag?

**Comment by kyhavlov** [comment]
No, the node won't be counted as an external node without that field set which means ESM won't run health checks for it.

**Comment by KEZHwMlXV1vFzs6QvY8v5WjX5** [comment]
the address that is set on the node name worker1.xxx.xxx.xxx_dev-app1.test.com ist valid even tho consul seems not to be able to ping it. I'm suspecting consul to trying to resolve the worker1.xxx.xxx.xxx_dev-app1.test.com name...

**Comment by nitharsandvag** [comment]
@kyhavlov 
This is our json file to create the Health Checks:
`{
  "Node": "worker1.xxx.xxx.xxx_dev-app1.test.com",
  "Datacenter": "test",
  "Address": "worker1.app1.test.com",
  "NodeMeta": {
    "external-node": "true",
    "external-probe": "true"
  },
  "Service": {
    "ID": "tomcat-id",
    "Service": "tomcat-service",
    "Tags": ["urlprefix- /sample"],
    "Address": "worker1.app1.test.com",
    "Port": 8080
  },
  "Checks": [{
    "CheckID": "worker1.checkidtest",
    "status": "passing",
    "ServiceID": "tomcat-id",
    "Definition": {
      "http": "http://worker1.app1.test.com:8080/",
      "interval": "10s",
       "Timeout": "5s"
    }
  }]
}`

We want to create external health check but disable the node ping, since Node name has invalid format in our case.
Consul-esm is not pinging the node address for sure.

**Comment by nitharsandvag** [comment]
any update on this?
I have created one more dummy test and the result is:
Dec 04 12:06:34 xxxxx docker[63679]: 2018/12/04 12:06:34 [WARN] could not ping node "tomcat_test:new-223": ping to "xxxxx" timed out

Would be nice of you can fix the bug soon.

**Comment by kyhavlov** [comment]
The ESM agent is definitely pinging the node address: https://github.com/hashicorp/consul-esm/blob/master/coordinate.go#L97

The original `socket: permission denied` and `ping to "xxxxx" timed out` errors could be caused by a few different things:
- The kernel settings on the ESM host (or the destination) don't allow ICMP pings. Make sure you can run just a `ping` command between the hosts normally if you're using socket mode for the pings in the ESM config.
- There could be an iptables rule blocking the ping on either the source or destination node.
- A firewall rule or security group rule could be in the way.

You can also try changing the `ping_type` setting in the config file to see if the regular UDP ping can get through instead.

**Comment by nitharsandvag** [comment]
It is already set to udp: ping_type = "udp"
normal ping to the node address is working fine.
I will check with icmp.
