### ISSUE TITLE
multi k8s cluster esm deployment?

### ISSUE THREAD

**Issue by killcity** [hashicorp/consul-esm#44]
We are running the same services on multiple k8s clusters, advertising to a single consul cluster via esm. esm is only running on a single cluster. Can esm be run reliably across every cluster without any weird health check collisions, etc? Every cluster esm deployment would be sidecar'd to a consul-agent calling the same consul cluster. We'd like to be able to have HA across the clusters in the event we lose the one that esm is deployed out to.

**Comment by lornasong** [comment]
Hi @killcity - thanks for the question and apologies for the delay.

Each cluster operates with its own catalog, and Consul does not share/replicate this data with other clusters. This means that if running esm on each cluster, you would need to register the external health check with each cluster. Each cluster then independently monitors the external health check. This would lead to redundant checks since each cluster is checking the same health checks. There is potential for the same health check to happen simultaneously but no weird health check collisions.

Issues on Github for consul-esm are intended to be related to bugs or feature requests. For questions in the future, you can use the Consul section of the [HashiCorp forum](https://discuss.hashicorp.com/c/consul).
