### ISSUE TITLE
standardize -version output

### ISSUE THREAD

**Issue by eikenb** [hashicorp/consul-esm#87]
We should have the first line of the `-version` output be the same across all our team's projects. It should look something like.. "consul-esm v0.3.3 (17c7ce4a)"

**Comment by lornasong** [comment]
@eikenb just a couple question for clarification

The output should be the same for a development vs. release binary, is that right? I like the output you suggest and it looks like consul-template follows this. Just double-checking because I noticed Consul outputs something like `Consul v1.7.2` for released vs. `Consul v1.6.1-224-g1f3f9a784` for development.

The [PR](https://github.com/hashicorp/consul-esm/pull/99) for this also includes an option for a version-prerelease value in the output e.g. `0.5.0-dev`. It looks like it would be useful to distinguish the released version from one in development, and CTS could follow the same pattern and use it for tech preview & beta. Let me know what your thoughts are!

Thanks!

**Comment by eikenb** [comment]
> The output should be the same for a development vs. release binary, is that right?

Yes. (same format, commit-id would be different)

> Just double-checking because I noticed Consul outputs something like [...]

Indeed Consul outputs something different... I don't know if we want to follow it's example exactly as the short-branch does add some useful information. I was mainly concerned with getting all our projects formatting it the same but, feel free to chime in if you disagree, IMO our version of the version output is better.

> [..] an option for a version-prerelease value in the output e.g. `0.5.0-dev`.

:thinking:
I can see the value of having version annotations for pre-release/beta/etc. But I'm not sure I see the utility in adding `-dev`.

@findkim what do you think? Should we add `-dev` to our non-versioned releases?

**Comment by lornasong** [comment]
@eikenb thanks for confirming! I agree, I prefer this version of version output and am happy to go with it.

On `-dev`, the only utility I can think of is that it would distinguish development versions from release version since those don't have an annotation either. I'm guessing this confusion will not often take place. I'm happy to go either way on it. @findkim interested in your thoughts on this as well

**Comment by findkim** [comment]
While we're looking for prior art, [Terraform uses `-dev`](https://github.com/hashicorp/terraform/blob/master/version/version.go#L19)! I find it very useful for local development. It helps me distinguish between binary versions from an official release to the one I'm currently tinkering with (both in the logs and `-version` flag).

It will also help clarify if a community member reports a bug ticket it'll quickly show if it's a non-release. For example, they built off of master or a feature branch.

For me, 👍 to include name + commit and 👍 to `-dev` for non-versioned releases.

**Comment by eikenb** [comment]
Yay, someone with a strong opinion (thanks @findkim).

**Comment by lornasong** [comment]
Thanks @findkim for pointing out the prior art! I also particularly like your point about a bug ticket for a non-release binary.
