### ISSUE TITLE
Must provide node and address

### ISSUE THREAD

**Issue by vassilvk** [hashicorp/consul-esm#9]
Using the example configuration, I get some unexpected results:
1. The `consul-esm` daemon periodically logs messages:
  *  `[ERR] http: Request PUT /v1/catalog/register, error: Must provide node and address from=127.0.0.1:60372`
  *  `[WARN] error updating node: could not update external node check for node "foo": Unexpected response code: 500 (Must provide node and address)`
  * `[WARN] could not update coordinate for node "foo": error applying coordinate update for node "foo": Unexpected response code: 404 ()`
2. Service `web` is registered and both its `Web HTTP check` and `Web TCP check` health-checks are set as passing although there is nothing listening on `localhost:8000`. I'd expect to see failing checks.

And I have a general question - how is ESM supposed to check the health of an external system with a health-check definition such as "http://localhost:8000/health"?
Isn't it supposed to hit the service on its external address?

**Comment by kyhavlov** [comment]
That error (`Must provide node and address`) is likely happening because you're using an older version of Consul; anything from v1.0.1 onwards should have the API change to allow the partial node update that the ESM relies on. It probably can't update the status of those failing health checks because of this, too.

You're right that the ESM is supposed to hit the service's external address; the example/README are a little confusing on this point (it's set up running a local Consul agent/ESM with the external services to be checked configured on the same machine). I'll try to improve the example to make this more clear. Hope that helps!

**Comment by vassilvk** [comment]
Thank you @kyhavlov!
That was it - switching from Consul 1.0.0 to 1.0.6 solved the issue 💯
